### ISSUE TITLE
migrate application to use mocha + sinon-chai testing frameworks

### ISSUE THREAD

**Issue by thescientist13** [kenzanmedia/angularjs-webpack-seed#1]
as both **Jasmine** and **Mocha** are popular JavaScript unit testing frameworks, having a working example to use as a reference would be valuable.  Currently this seed uses **Jasmine**.

In particular, I would like to validate a working example that includes the use of **sinon-chai** specific APIs in unit tests, that should still work with [karma-webpack](https://github.com/webpack-contrib/karma-webpack)
https://github.com/kenzanmedia/angularjs-webpack-seed/blob/master/karma.conf.js#L28

The error(s) I was getting was 
```
Chrome 58.0.3029 (Mac OS X 10.12.4) ERROR
  Uncaught ReferenceError: sinon is not defined

# and

Chrome 58.0.3029 (Mac OS X 10.12.4) ERROR
  Uncaught TypeError: Cannot read property 'should' of undefined
  at node_modules/karma-chai/adapter.js:77

```

bonus points:
since `angular` gets imported through vendor.js, I think it could be removed from here, yes?
https://github.com/kenzanmedia/angularjs-webpack-seed/blob/master/karma.conf.js#L19

**Comment by thescientist13** [comment]
I seem to have made a little progress on this myself, though still need a little more time before I can provide a full update.

**Comment by thisgeek** [comment]
@thescientist13 Groovy.  Have at!

**Comment by thescientist13** [comment]
So lessons learned
1. the `preprocessors` glob is too greedy, and it was trying process all files from _node_modules_ as well.  this is likely what was causing the actual error above
1. karma-webpack ONLY acts as a preprocessor, it will not recognize entry points in webpack config.  This was a false understanding on my part, so lesson learned here is RTFM
1.  since karma-webpack only does preprocessing, certain vendor files still needed to be included in `files` in _karma.conf.js_
1. to leverage our

So all together, this is what I ended up with in my _karma.conf.js_
```javascript
const isProductionBuild = process.env.NODE_ENV === 'production';
const shouldWatch = !isProductionBuild;
const shouldSingleRun = isProductionBuild;
const browser = isProductionBuild ? 'PhantomJS' : 'Chrome';
const webpackConfig = require('./webpack.config.common');

// TODO issues with karma and CommonChunksPlugin
// https://github.com/webpack/karma-webpack/issues/24
webpackConfig.plugins[webpackConfig.plugins.length - 1] = function() {};

// dont fail on eslint errors while developing
webpackConfig.module.rules[0].use[1].options.failOnError = isProductionBuild;

module.exports = function(config) {
  const logLevel = isProductionBuild ? config.LOG_DEBUG : config.LOG_INFO;

  config.set({
    basePath: './',
    frameworks: ['mocha', 'sinon-chai'],
    files: [
      // included here to ensure proper loading order and availablity of jquery + angular + mocks to Karma
      { pattern: './node_modules/jquery/dist/jquery.js', watched: false },
      { pattern: './node_modules/angular/angular.js', watched: false },
      { pattern: './node_modules/angular-mocks/angular-mocks.js', watched: false },
      { pattern: './src/index.js', watched: true },
      { pattern: './src/modules/**/*.spec.js', watched: true }
    ],

    preprocessors: {
      'src/**/*.js': ['webpack', 'sourcemap', 'coverage']
    },

    webpack:  webpackConfig,

    reporters: ['progress', 'dots', 'junit', 'coverage'],
    port: 9876,
    browserDisconnectTolerance : 1,
    logLevel: logLevel,
    autoWatch: shouldWatch,
    browsers: [browser],
    singleRun: shouldSingleRun,
    concurrency: Infinity,
    junitReporter: {
      outputDir: './reports/',
      outputFile: 'test-results/test-results.xml',
      suite: 'wui.components.header',
      useBrowserName: false
    },
    coverageReporter: {
      type : 'cobertura',
      dir : './reports',
      subdir: 'test-coverage/phantomjs',
      file: 'coverage.xml'
    }
  });

};
```

cc: @thisgeek

**Comment by thescientist13** [comment]
let's apply some of these change to this project to keep our reference sample up to date
