### ISSUE TITLE
array.find failing phantomjs

### ISSUE THREAD

**Issue by thescientist13** [kenzanmedia/angularjs-webpack-seed#16]
not sure if it's the case here, but running **phantomjs** in Jenkins in another project required this polyfill for `Array.find`
https://www.npmjs.com/package/phantomjs-polyfill-find

**Comment by thisgeek** [comment]
It didn't occur to me to check `NODE_ENV=production yarn test:unit`. It does in fact fail on find.

```
 PhantomJS 2.1.1 (Mac OS X 0.0.0) tgh.services.users should test that getPrimaryUser call works as expected FAILED
.       undefined is not a constructor (evaluating 'this.users.find(function(user){__cov_nyZ7phEvVkhpiWSATBomOg.f['18']++;__cov_nyZ7phEvVkhpiWSATBomOg.s['52']++;return user.isPrimary;})')
	getPrimaryUser@src/services/users/users.service.spec.js:9:12982
	src/services/users/users.service.spec.js:9:15706
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 9 of 12 (1 FAILED) (0 secs / 0.003 secs)
```

**Comment by thisgeek** [comment]
@thescientist13 What's the browser support model? We'll have to polyfill for IE11 and Android if you want those. See <https://kangax.github.io/compat-table/es6/#test-Array.prototype_methods_Array.prototype.find_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;>
