### ISSUE TITLE
How can i add or load images in the app?

### ISSUE THREAD

**Issue by nhuthuynh** [kenzanmedia/angularjs-webpack-seed#22]
Hi guys,
How can i add images in html template of my angular app using this repo? I try to use file loader and copywebpack plugin but they do not work as expected. The following is my config

**my folder structure**

<img width="376" alt="screen shot 2018-10-30 at 8 39 16 pm" src="https://user-images.githubusercontent.com/3124346/47709246-f68c0c80-dc83-11e8-9747-2fd5546edced.png">

**load image failed** 

<img width="605" alt="screen shot 2018-10-30 at 8 41 32 pm" src="https://user-images.githubusercontent.com/3124346/47709394-423eb600-dc84-11e8-9a41-986f1b504b0f.png">

**webpack.config.develop.js**

```
const path = require('path');
const webpackMerge = require('webpack-merge');
const commonConfig = require('./webpack.config.common.js');

module.exports = webpackMerge(commonConfig, {
  output: {
    path: path.join(__dirname, '/build'),
    publicPath: '/',
    filename: '[name].bundle.js',
    sourceMapFilename: '[name].map',
    chunkFilename: '[id].chunk.js',
    library: 'ac_[name]',
    libraryTarget: 'var'
  },

  watch: true,

  devServer: {
    contentBase: 'npm install image-webpack-loader file-loader --save-dev/build',
    compress: true,
    port: 9000,
    host: 'localhost',
    historyApiFallback: true,
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    },
    proxy: {
      '/api/*': {
        target: 'http://<your-domain>',
        secure: false,
        changeOrigin: true
      }
    }
  }

});
```

**webpack.config.common.js**
```
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  context: path.resolve(__dirname, 'src'),

  entry: {
    index: './index.js',
    vendor: './vendor.js'
  },

  module: {
    rules: [{
      test: /\.js$/,
      exclude: /node_modules/,
      use: [{
        loader: 'babel-loader',
        options: {
          presets: [
            ['es2015', { modules: false }]
          ]
        }
      }, {
        loader: 'eslint-loader',
        options: {
          failOnWarning: true,
          failOnError: true
        }
      }]
    }, {
      test: /\.html$/,
      use: [{
        loader: 'html-loader'
      }]
    }, {
      test: /\.scss$/,
      loader: ['style-loader', 'css-loader', 'sass-loader']
    }, {
      test: /\.(jpe?g|png|gif|svg)$/i,
      loader: ['file', 'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false']
    }]
  },

  plugins: [
    new FaviconsWebpackPlugin({
      logo: './components/bootstrap/images/favicon.png',
      emitStats: true,
      prefix: 'icons/',
      statsFilename: 'icons/stats.json',
      inject: true,
      title: 'Weather Forecast',
      background: '#efefef',
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: false,
        favicons: true,
        firefox: true,
        opengraph: true,
        twitter: true,
        yandex: true,
        windows: true
      }
    }),

    new HtmlWebpackPlugin({
      template: './index.html',
      chunksSortMode: 'dependency'
    }),

    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor'].reverse()
    }),

    new CopyWebpackPlugin([{
      from: '/src/images',
      to: '/build/images'
    }])
  ]

};
```

**webpack.config.prod.js**
```
const path = require('path');
const commonConfig = require('./webpack.config.common');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const UglifyJsPlugin = require('webpack/lib/optimize/UglifyJsPlugin');
const WebpackMd5Hash = require('webpack-md5-hash');
const webpackMerge = require('webpack-merge');
const NgAnnotatePlugin = require('ng-annotate-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

module.exports = webpackMerge(commonConfig, {

  devtool: 'source-map',

  output: {
    path: path.join(__dirname, '/build'),
    publicPath: '/',
    filename: '[name].[chunkhash].bundle.js',
    sourceMapFilename: '[name].[chunkhash].bundle.map',
    chunkFilename: '[id].[chunkhash].chunk.js'
  },

  plugins: [
    new NgAnnotatePlugin({
      add: true
    }),
    new WebpackMd5Hash(),
    new UglifyJsPlugin({
      beautify: false,
      mangle: { screw_ie8: true, keep_fnames: true }, // eslint-disable-line camelcase
      compress: { screw_ie8: true }, // eslint-disable-line camelcase
      comments: false,
      sourceMap: true
    }),
    new ExtractTextPlugin('[name].[chunkhash].style.css'),
    new BundleAnalyzerPlugin({
      analyzerMode: 'disabled',
      generateStatsFile: true
    })
  ]

});
```

**Comment by thescientist13** [comment]
Hey @nhuthuynh , thanks for the question!

Can you show how your images are being referenced in your code?  From the sounds of it, something like?
```html
<a href="/path/to/image">
```

I haven't good luck with **webpack** processing paths embedded in HTML like this.  In general, I always had best results as you did, using file-loader but using `import` to pull in the image.  In this way, there was no need to use `CopyWebpackPlugin`

example:
```javascript
# my-component..js
import image from './path/to/image.png';
import template from './my-component.template.html';

export default class HeaderComponent {
  constructor() {
    this.template = template;
    this.restrict = 'E';
    this.myImage = image;
  }
}
```

```html
<!-- my-component.template.html -->
<a href="{{myImage}}">
```

Also, when using **webpack** and paths, note my use of `'./`.  This ensures more precise filesystem lookups for these asset types by **webpack**.

Another option is to reference the image from your CSS, using `url`, ex.
```css
.my-component {
  background-image: url('./path/to/image.png');
}
```

Hope that helps!

**Comment by thescientist13** [comment]
Also, if you can, try and upgrade to **webpack** 4, it removes a lot of the need / complexity of having to setup `CommonsChunkPlugin`.  If you're interested, I can make those changes [upstream](https://github.com/thegreenhouseio/angularjs-webapp-seed) for you.

**Comment by nhuthuynh** [comment]
Hi @thescientist13 thank you for your suggestion, but it is not a good practice because if there are any images I do not use will not be loaded to the build folder and I dynamically load the weather image based on the related dates data from JSON file.

**My folder structure**

<img width="191" alt="screen shot 2018-10-31 at 7 58 05 am" src="https://user-images.githubusercontent.com/3124346/47750449-87460500-dce3-11e8-879c-7489e3a6a886.png">
<img width="322" alt="screen shot 2018-10-31 at 7 58 22 am" src="https://user-images.githubusercontent.com/3124346/47750451-87460500-dce3-11e8-9044-22234a0faf64.png">
<img width="318" alt="screen shot 2018-10-31 at 7 58 54 am" src="https://user-images.githubusercontent.com/3124346/47750452-87de9b80-dce3-11e8-92e5-afd5693b97c4.png">

I use the WeatherService to return weather image in folder images
**WeatherService function**
<img width="322" alt="screen shot 2018-10-31 at 8 00 41 am" src="https://user-images.githubusercontent.com/3124346/47750454-88773200-dce3-11e8-81a3-a9a55134c2a0.png">
**WeatherOfDate directive template**
<img width="1143" alt="screen shot 2018-10-31 at 8 00 11 am" src="https://user-images.githubusercontent.com/3124346/47750447-86ad6e80-dce3-11e8-8c57-309875cb6265.png">
**WeatherOfDate directive controller**
<img width="475" alt="screen shot 2018-10-31 at 7 59 40 am" src="https://user-images.githubusercontent.com/3124346/47750453-87de9b80-dce3-11e8-8e40-5b5f0707b706.png">

**Comment by nhuthuynh** [comment]
> Also, if you can, try and upgrade to **webpack** 4, it removes a lot of the need / complexity of having to setup `CommonsChunkPlugin`. If you're interested, I can make those changes [upstream](https://github.com/thegreenhouseio/angularjs-webapp-seed) for you.

It would be great! because i am new to webpack and this is my chance to learn it! thanks a lot!

**Comment by thescientist13** [comment]
I'll take a look that as well this weekend.

**Comment by thescientist13** [comment]
@nhuthuynh 
Regarding copy webpack plugin, I think you might want to point the `to` directory to your _build/_ directory.  Also, considering using `path.join` and `__dirname` as much as possible when setting paths.

```javascript
 new CopyWebpackPlugin([{
      from: path.join(__dirname, 'src', 'images'),
      to: path.join(__dirname, 'build', 'images')
    }]),
```

**Comment by nhuthuynh** [comment]
@thescientist13 thanks for your effort! It works perfectly!
