### ISSUE TITLE
implement an example of lazy-loading

### ISSUE THREAD

**Issue by thescientist13** [kenzanmedia/angularjs-webpack-seed#3]
Lazy loading and bundling strategies are important to have good familiarity with.  Let's implement lazy loading as a reference.  This is a library that we've had success with, so let's go with that one first
https://github.com/ocombe/ocLazyLoad

**Comment by thisgeek** [comment]
Note to self:

The [Webpack page](https://oclazyload.readme.io/docs/webpack) under the Advanced Usage section of the ocLazyLoad documentation wants editing. As of this writing, it merely points to two example projects:

* [express-webpack2-angularMaterial-oclazyload](https://github.com/preciousDev/angularMaterial-webpack2-ocLazyLoad)
* [webpack-angular-oclazyload](https://github.com/ay13/webpack-angular-oclazyload)

At a first glance, it looks like the first example lazy loads modules in the resolver of [each](https://github.com/preciousDev/angularMaterial-webpack2-ocLazyLoad/blob/master/app-content/main/main.js#L30-L32) [route](https://github.com/preciousDev/angularMaterial-webpack2-ocLazyLoad/blob/master/app-content/main/main.js#L58-L60). Nothing jumped out at me in the webpack config, but it may warrant a closer inspection. I plan to get it running and see what there is to see.

**Comment by thescientist13** [comment]
Cool.

I know in a project we've managed to use Webpack with ocLazyLoad but it wasn't a pure Webpack build (was a hybrid approach with Gulp... a lesson learned there 🙄 ), so hopefully in this instance we may get a cleaner more direct path to a good solution.

**Comment by thisgeek** [comment]
Progress update: The current lint configuration rejects use of the [dynamic import](https://webpack.js.org/guides/code-splitting-async/#dynamic-import-import-) with this error:

```
Parsing error: 'import' and 'export' may only appear at the top level
```

I'll have to find my way around that. Might be able to disable it with a comment for the time being but it would be good to have a more permanent solution.

**Comment by thescientist13** [comment]
somewhat related, and thought it would be a good read
https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31
