### ISSUE TITLE
lint top-level JS files

### ISSUE THREAD

**Issue by thisgeek** [kenzanmedia/angularjs-webpack-seed#8]
Currently the configuration files do not follow the same lint rules as the rest of the source:

```
$ eslint src *.js

angularjs-webpack-seed/karma.conf.js
   7:1  warning  Unexpected 'todo' comment           no-warning-comments
   7:1  warning  Unexpected ' TODO' comment          no-warning-comments
  10:1  error    More than 1 blank line not allowed  no-multiple-empty-lines
  44:7  error    Extra space after key 'type'        key-spacing
  45:7  error    Extra space after key 'dir'         key-spacing

angularjs-webpack-seed/webpack.config.common.js
  24:10  error  Unexpected trailing comma                comma-dangle
  33:14  error  Extra space before value for key 'test'  key-spacing

angularjs-webpack-seed/webpack.config.develop.js
   6:11  error  Use path.join() or path.resolve() instead of + to create paths  no-path-concat
  11:25  error  Unexpected trailing comma                                       comma-dangle
  24:11  error  Missing space before value for key 'proxy'                      key-spacing

angularjs-webpack-seed/webpack.config.prod.js
   2:35  error  Strings must use singlequote                                    quotes
  13:11  error  Use path.join() or path.resolve() instead of + to create paths  no-path-concat
  16:47  error  Unexpected trailing comma                                       comma-dangle
  26:17  error  Extra space after key 'screw_ie8'                               key-spacing
  26:17  error  Identifier 'screw_ie8' is not in camel case                     camelcase
  26:35  error  Identifier 'keep_fnames' is not in camel case                   camelcase
  27:19  error  Identifier 'screw_ie8' is not in camel case                     camelcase

✖ 17 problems (15 errors, 2 warnings)
```

**Comment by thescientist13** [comment]
i wonder if there's a loader for that?  🤔 🤣

**Comment by thisgeek** [comment]
Ha!

Though, that's just the thing. What should you do to ensure something in the pipeline lints the config files? The seed project only protects that which it bundles with [eslint-loader](https://www.npmjs.com/package/eslint-loader), and so it should.

We might change the build task to run a lint check. Instead of:

```bash
rimraf ./build && webpack --config ./webpack.config.prod.js
```

fail the script before packing if anything in the top level fails:

```bash
rimraf ./build && eslint *.js && webpack --config ./webpack.config.prod.js
```

**Comment by thescientist13** [comment]
sold!  💰

**Comment by thescientist13** [comment]
should we make sure we explicitly depend on a version of `eslint` in _package.json_?
https://github.com/kenzanmedia/angularjs-webpack-seed/blob/master/package.json#L38

it should come in with **eslint-loader** so....

**Comment by thisgeek** [comment]
But wait, there's more!

I expect you don't want to break the build over warnings in the config. I could add the `--quiet` flag for that.

**Comment by thisgeek** [comment]
I saw eslint 3 set here: https://github.com/kenzanmedia/angularjs-webpack-seed/blob/master/package.json#L45

**Comment by thisgeek** [comment]
My mistake: I thought omitting `--quiet` meant eslint would set an error code, but I was mistaken. It just prints the warnings and moves one, which now I think on it makes more sense.

**Comment by thescientist13** [comment]
ah, good catch, I looked too quickly.  I recall it being required as `peerDependency` so we would see warnings and failed builds with `eslint-loader` if we didn't.
